services:
  - type: web
    name: nexa-platform
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build && echo "Build completed successfully"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: NEXA
      - key: LANGCHAIN_TRACING_V2
        value: true
      - key: NEXT_PUBLIC_DRAWIO_URL
        value: https://app.diagrams.net
