import jsPDF from 'jspdf'

export interface BasicPDFData {
  title: string
  engineer: string
  client: string
  date: string
}

export function generateBasicPDF(data: BasicPDFData): jsPDF {
  // Create new PDF document
  const doc = new jsPDF()
  
  // Set font
  doc.setFont('helvetica')
  
  // Title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('NEXA Solution Report', 20, 30)
  
  // Subtitle
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text('Basic Information', 20, 50)
  
  // Basic info as bullet points
  doc.setFontSize(11)
  const startY = 70
  const lineHeight = 15
  
  const bulletPoints = [
    `• Project Title: ${data.title}`,
    `• Prepared By: ${data.engineer}`,
    `• Prepared For: ${data.client}`, 
    `• Date: ${formatDate(data.date)}`
  ]
  
  bulletPoints.forEach((point, index) => {
    doc.text(point, 25, startY + (index * lineHeight))
  })
  
  // Footer
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  doc.text('Generated by NEXA Platform', 20, 280)
  
  return doc
}

export function generateBasicPDFBlob(data: BasicPDFData): Blob {
  const doc = generateBasicPDF(data)
  return doc.output('blob')
}

export function generateBasicPDFDataURI(data: BasicPDFData): string {
  const doc = generateBasicPDF(data)
  return doc.output('datauristring')
}

function formatDate(dateString: string): string {
  try {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long', 
      day: 'numeric'
    })
  } catch {
    return dateString
  }
}



